-- Creating classroom_locations table
CREATE TABLE IF NOT EXISTS classroom_locations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_code VARCHAR(20) NOT NULL UNIQUE,
    room_name VARCHAR(100) NOT NULL,
    building VARCHAR(50) NOT NULL,
    floor VARCHAR(10) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Inserting data for Hill Campus locations
INSERT INTO classroom_locations (room_code, room_name, building, floor, description) VALUES
('B2LAB2', 'Lab2', 'Back', '1', 'Lab: Auto-Cad Lab'),
('B2FR1', 'Faculty room', 'Back', '1', 'Staff room'),
('B2CR201', 'CR201', 'Back', '1', 'Classroom'),
('B2CR202', 'CR202', 'Back', '1', 'Classroom'),
('B2CR203', 'CR203', 'Back', '1', 'Classroom'),
('B2CR204', 'CR204', 'Back', '1', 'Classroom'),
('B2CR205', 'CR205', 'Back', '1', 'Classroom'),
('B2ERP1', 'ERPcell', 'Back', '1', 'Enquiry area'),
('B2CL8', 'Lab8', 'Back', '1', 'Lab'),
('B2S1', 'BackStair1', 'Back', '1', 'Stairs'),
('B2S2', 'BackStair2', 'Back', '1', 'Stairs'),
('F2CR207', 'CR207', 'Front', '1', 'Classroom'),
('F2CR206', 'CR206', 'Front', '1', 'Classroom'),
('F2LT201', 'LT201', 'Front', '1', 'Lecture Theatre'),
('F2LT202', 'LT202', 'Front', '1', 'Lecture Theatre'),
('F2PAN1', 'Pantry', 'Front', '1', 'Pantry'),
('F2TCL12', 'TCL12', 'Front', '1', 'Lab: Thin Client Lab'),
('F2LIB1', 'Library', 'Front', '1', 'Study Point'),
('F2CO1', 'ChancellorOffice', 'Front', '1', 'Chancellor''s office'),
('F2VCO1', 'Vice-ChancellorOffice', 'Front', '1', 'Vice Chancellor''s office'),
('F2S1', 'FrontStair1', 'Front', '1', 'Stairs'),
('F2S2', 'FrontStair2', 'Front', '1', 'Stairs'),
('F2CS1', 'CircularStair1', 'Front', '1', 'Stairs'),
('F2CS2', 'CircularStair2', 'Front', '1', 'Stairs'),
('M2SR1', 'ServerRoom', 'Middle', '1', 'Enquiry area'),
('M2SR2', 'StaffRoom', 'Middle', '1', 'Staff room'),
('M2S1', 'MidStair', 'Middle', '1', 'Stairs'),
('B3PHARM1', 'Pharmacology', 'Back', '2', 'Lab'),
('B3PHARMCHEM', 'PharmaceuticalChemistry1', 'Back', '2', 'Lab'),
('B3PHARMC2', 'Pharmaceutics2', 'Back', '2', 'Lab'),
('B3PHARMC1', 'Pharmaceutics1', 'Back', '2', 'Lab'),
('B3PHARMCOG1', 'Pharmacognosy1', 'Back', '2', 'Lab'),
('B3CL7', 'Lab7', 'Back', '2', 'Lab'),
('B3CL3', 'Lab3', 'Back', '2', 'Lab'),
('B3S1', 'BackStair1', 'Back', '2', 'Stairs'),
('B3S2', 'BackStair2', 'Back', '2', 'Stairs'),
('F3DFA', 'DeptofFineArts', 'Front', '2', 'Staff room'),
('F3LT302', 'LT302', 'Front', '2', 'Lecture Theatre'),
('F3CR305', 'CR305', 'Front', '2', 'Classroom'),
('F3CR301', 'CR301', 'Front', '2', 'Classroom'),
('F3LT301', 'LT301', 'Front', '2', 'Lecture Theatre'),
('F3CR303', 'CR303', 'Front', '2', 'Classroom'),
('F3CR302', 'CR302', 'Front', '2', 'Classroom'),
('F3NHSTAFF', 'NewHall', 'Front', '2', 'Staff room'),
('F3CR304', 'CR304', 'Front', '2', 'Classroom'),
('F3DVAG', 'DeptofVisualArtsandGaming', 'Front', '2', 'Staff room: A&G Dept. Seating Area'),
('F3S1', 'FrontStair1', 'Front', '2', 'Stairs'),
('F3S2', 'FrontStair2', 'Front', '2', 'Stairs'),
('F3CS1', 'CircularStair1', 'Front', '2', 'Stairs'),
('F3CS2', 'CircularStair2', 'Front', '2', 'Stairs'),
('M3SR1', 'StaffRoom1', 'Middle', '2', 'Staff room'),
('M3SR2', 'StaffRoom2', 'Middle', '2', 'Staff room'),
('M3S1', 'MidStair', 'Middle', '2', 'Stairs'),
('B4CLIOT', 'IoTLab', 'Back', '3', 'Lab: Internet of Things Lab'),
('B4CR401', 'CR401', 'Back', '3', 'Classroom'),
('B4FACRDM', 'Faculty room(Maths)', 'Back', '3', 'Staff room'),
('B4ELECTRICALLAB1', 'ElectricalLab', 'Back', '3', 'Lab'),
('B4LD&MPLAB', 'LDlab', 'Back', '3', 'Lab'),
('B4ELECTRONICLAB', 'ElectronicsLab', 'Back', '3', 'Lab'),
('B4CR402', 'CR402', 'Back', '3', 'Classroom'),
('B4BTECHHOD1', 'BtechHODFirst', 'Back', '3', 'Enquiry Area'),
('B4CL4', 'Lab4', 'Back', '3', 'Lab'),
('B4S1', 'BackStair1', 'Back', '3', 'Stairs'),
('B4S2', 'BackStair2', 'Back', '3', 'Stairs'),
('F4CR403', 'CR403', 'Front', '3', 'Classroom'),
('F4LT401', 'LT401', 'Front', '3', 'Lecture Theatre'),
('F4CR404', 'CR404', 'Front', '3', 'Classroom'),
('F4DEPTCSE', 'DeptofCSE', 'Front', '3', 'Staff room'),
('F4MACL1', 'MAClab', 'Front', '3', 'Lab'),
('F4CR405', 'CR405', 'Front', '3', 'Classroom'),
('F4TCL34', 'TCL34', 'Front', '3', 'Lab: Thin Client Lab'),
('F4LT402', 'LT402', 'Front', '3', 'Lecture Theatre'),
('F4CR406', 'CR406', 'Front', '3', 'Classroom'),
('F4S1', 'FrontStair1', 'Front', '3', 'Stairs'),
('F4S2', 'FrontStair2', 'Front', '3', 'Stairs'),
('F4CS1', 'CircularStair1', 'Front', '3', 'Stairs'),
('F4CS2', 'CircularStair2', 'Front', '3', 'Stairs'),
('M4SR1', 'Staff Room1', 'Middle', '3', 'Staff Room'),
('M4SR2', 'Staff Room2', 'Middle', '3', 'Staff Room'),
('M4S1', 'MidStair', 'Middle', '3', 'Stairs'),
('B5CR501', 'CR501', 'Back', '4', 'Classroom'),
('B5PHYHOD', 'PhysicsHOD', 'Back', '4', 'Enquiry Area'),
('B5PHYLAB', 'PhysicsLab', 'Back', '4', 'Lab'),
('B5CL5', 'Lab5', 'Back', '4', 'Lab'),
('B5IAPTLAB', 'IAPTLab', 'Back', '4', 'Lab: Indianasm Indian Asian Physics Olympaid Lab'),
('B5CR502', 'CR502', 'Back', '4', 'Classroom'),
('B5FR1', 'FacultyRoom', 'Back', '4', 'Staff room: Physics Dept. Seating'),
('B5CHEMLAB', 'ChemistryLab', 'Back', '4', 'Lab'),
('B5S1', 'BackStair1', 'Back', '4', 'Stairs'),
('B5S2', 'BackStair2', 'Back', '4', 'Stairs'),
('F5CR503', 'CR503', 'Front', '4', 'Classroom'),
('F5LT501', 'LT501', 'Front', '4', 'Lecture Theatre'),
('F5HODFD', 'HODFaishonDesign', 'Front', '4', 'Enquiry Area: Fasion Design Dept. Seating'),
('F5NFDCR1', 'FDCR', 'Front', '4', 'Classroom: Fasion Deisgn CR'),
('F5GCL1', 'GCLab1', 'Front', '4', 'Lab: Garment Consutruction Lab'),
('F5GCL2', 'GCLab2', 'Front', '4', 'Lab: Garment Consutruction Lab'),
('F5LT502', 'LT502', 'Front', '4', 'Lecture Theatre'),
('F5CR504', 'CR504', 'Front', '4', 'Classroom'),
('F5S1', 'FrontStair1', 'Front', '4', 'Stairs'),
('F5S2', 'FrontStair2', 'Front', '4', 'Stairs'),
('F5CS1', 'CircularStair1', 'Front', '4', 'Stairs'),
('F5CS2', 'CircularStair2', 'Front', '4', 'Stairs'),
('M5SR1', 'StaffRoom1', 'Middle', '4', 'Staff room'),
('M5SR2', 'StaffRoom2', 'Middle', '4', 'Staff room'),
('M5S1', 'MidStair', 'Middle', '4', 'Stairs'),
('B6FR1', 'Facultyroom', 'Back', '5', 'Staff room'),
('B6CR601', 'CR601', 'Back', '5', 'Classroom'),
('B6CR602', 'CR602', 'Back', '5', 'Classroom'),
('B6CR603', 'CR603', 'Back', '5', 'Classroom'),
('B6CR604', 'CR604', 'Back', '5', 'Classroom'),
('B6CR605', 'CR605', 'Back', '5', 'Classroom'),
('B6LAWLIB', 'LawLibrary', 'Back', '5', 'Study Point'),
('B6S1', 'BackStair1', 'Back', '5', 'Stairs'),
('B6S2', 'BackStair2', 'Back', '5', 'Stairs'),
('F5NMATHSR', 'StaffRoomMaths', 'Front', '5', 'Staff room'),
('F5NSSOFC', 'NSSoffice', 'Front', '5', 'office'),
('F5NCCOFC', 'NCCoffice', 'Front', '5', 'office'),
('F5NA1', 'NewAudi', 'Front', '5', 'Hall'),
('F5MOOTC', 'MootCourt', 'Front', '5', 'Lab'),
('F5GREENROOOM', 'GreenRoom', 'Front', '5', 'Lab: (mass and media com lab)'),
('F5KPNAUTIYAL', 'KPaudi', 'Front', '5', 'Hall'),
('F5GLASS/GREEN', 'GlassRoom', 'Front', '5', 'Lab'),
('F5RDCELLOFC', 'RADcell', 'Front', '5', 'Staff room'),
('F5LT602', 'LT602', 'Front', '5', 'Lecture Theatre'),
('F5PDPSR', 'StaffRoomPDP', 'Front', '5', 'Staff room'),
('F5LAWSR', 'StaffRoomLaw', 'Front', '5', 'Staff room'),
('F5CR606', 'CR606', 'Front', '5', 'Classroom'),
('F5LT601', 'LT601', 'Front', '5', 'Lecture Theatre'),
('F5FR', 'FacultyRoom', 'Front', '5', 'Staff room'),
('F6S1', 'FrontStair1', 'Front', '5', 'Stairs'),
('F6S2', 'FrontStair2', 'Front', '5', 'Stairs'),
('F6CS1', 'CIRCULARSTAIR1', 'Front', '5', 'Stairs'),
('F6CS2', 'CIRCULARSTAIR2', 'Front', '5', 'Stairs'),
('M5SR12', 'StaffRoom12', 'Middle', '5', 'Staff room'),
('M5CL6', 'Lab6', 'Back', '5', 'lab'),
('M6S1', 'MidStair', 'Middle', '5', 'Stairs'),
('B0S1', 'BackStair1', 'Back', '-1', 'Stairs'),
('B0S2', 'BackStair2', 'Back', '-1', 'Stairs'),
('F0CRA', 'CR-A', 'Front', '-1', 'Classroom'),
('F0CRB', 'CR-B', 'Front', '-1', 'Classroom'),
('F0CCTVR', 'CCTVRoom', 'Front', '-1', 'Security Office'),
('F0PHDRCELL', 'PhDCell', 'Front', '-1', 'Enquiry Area'),
('F0REGISTRAR', 'RegistrarOffice(Basement)', 'Front', '-1', 'Enquiry Area'),
('F0FEECELL', 'FeeCell', 'Front', '-1', 'Fee related Enquiry Area'),
('F0IDCARD', 'ID-CardOffice', 'Front', '-1', 'ID-Card Enquiry Area'),
('F0EXAMINATIONCELL', 'Examination Cell(CoE)', 'Front', '-1', 'Enquiry Area'),
('F0LD&MPL2', 'ldlab2', 'Front', '-1', 'Lab'),
('F0CSR', 'CentralStaffRoom', 'Front', '-1', 'Enquiry Area'),
('F0CAO', 'CheifAdministrativeOffice', 'Front', '-1', 'Enquiry Area'),
('F0RRA', 'RR-A', 'Front', '-1', 'Classroom'),
('F0RRB', 'RR-B', 'Front', '-1', 'Classroom'),
('F0RRC', 'RR-C', 'Front', '-1', 'Classroom'),
('F0RRD', 'RR-D', 'Front', '-1', 'Classroom'),
('F0RRE', 'RR-E', 'Front', '-1', 'Classroom'),
('F0RRF', 'RR-F', 'Front', '-1', 'Classroom'),
('F0RRG', 'RR-G', 'Front', '-1', 'Classroom'),
('F0RRH', 'RR-H', 'Front', '-1', 'Classroom'),
('F0WORKSHOP', 'Workshop', 'Front', '-1', 'Lab'),
('F0MDLAB', 'ManualDrawingLab', 'Front', '-1', 'Lab'),
('F0CIVENGLAB', 'CivilEnggLab', 'Front', '-1', 'Lab'),
('F0FDWORKSHOP', 'FasionDesignWorkshop', 'Front', '-1', 'Lab'),
('F0S1', 'FrontStair1', 'Front', '-1', 'Stairs'),
('F0S2', 'FrontStair2', 'Front', '-1', 'Stairs'),
('F0S3', 'CircularStair1', 'Front', '-1', 'Stairs'),
('F0S4', 'CircularSTair2', 'Front', '-1', 'Stairs'),
('M0S1', 'MidStair', 'Middle', '-1', 'Stairs'),
('B1CR101', 'CR101', 'Back', '0', 'Classroom: just after back entry gate'),
('B1FR1', 'Faculty room', 'Back', '0', 'Not an Enquiry Office'),
('B1PAHRMCHEM2', 'Pharmaceutical chemistry 2', 'Back', '0', 'Lab: just after cr 101'),
('B1CR102', 'CR102', 'Back', '0', 'Classroom: after Instrumentation lab'),
('B1CR103', 'CR103', 'Back', '0', 'Classroom: after cr 102'),
('B1CR104', 'CR104', 'Back', '0', 'Classroom: after cr 103'),
('B1WIFIZONE', 'Wifi Zone', 'Back', '0', 'Sitting spot: in front of cr 102'),
('B1CL1', 'Lab1', 'Back', '0', 'Lab: left wing(from lift area)after CR 101'),
('B1CL10', 'Lab10', 'Back', '0', 'Lab: right wing(from lift area) after cr 103'),
('BPCO', 'PlacementCellOffice', 'Back', '0', 'Staff room: in front of cr 101'),
('B1S1', 'Stairs 13', 'Back', '0', 'Stairs'),
('B1S2', 'Stairs 14', 'Back', '0', 'Stairs'),
('F1RECEPTION', 'Reception area', 'Front', '0', 'Enquiry area: just after front gate entry'),
('F1OPENAUDI', 'open audi', 'Front', '0', 'Sitting spot: front open area'),
('F1GATE2', 'Gate No.-02', 'Front', '0', 'Entry Point'),
('F1MEETINGHALL', 'Meeting Hall', 'Front', '0', 'Hall'),
('F1GATE3', 'Gate No.-03', 'Front', '0', 'Entry Point'),
('F1RESEACHCELL', 'Research and Development cell', 'Middle', '0', 'Enquiry Area'),
('F1REGISTRAROFC2', 'Registrar Office', 'Middle', '0', 'Enqiery Area'),
('F1CR105', 'CR 105', 'Front', '0', 'Classroom'),
('F1BOSCH', 'Conference hall/BOSCH lab', 'Front', '0', 'Hall: Career Skills Lab'),
('F1SEMINARHALL', 'Seminar Hall', 'Front', '0', 'Hall'),
('F1MIROOM', 'MI Room', 'Front', '0', 'Medical emergency'),
('F1ADDCELL', 'Admission Enquiry', 'Front', '0', 'Enquiry area'),
('F1ADDCELL2', 'Administrative Area', 'Front', '0', 'Enquiry area'),
('F1UBUNTU', 'Computere Centre', 'Front', '0', 'Lab: Ubantu Lab'),
('F1S1', 'Stairs 8', 'Front', '0', 'Stairs'),
('F1S2', 'Stairs 9', 'Front', '0', 'Stairs'),
('F1CS1', 'Stairs 10(CIRCULAR STAIRS)', 'Front', '0', 'Stairs'),
('F1CS2', 'Stairs 11(CIRCULAR STAIRS)', 'Front', '0', 'Stairs'),
('M1GATE1', 'Gate No.-01', 'Middle', '0', 'Entry Point'),
('M1S1', 'Stairs 12', 'Middle', '0', 'Stairs');

-- Creating indexes for faster searches
CREATE INDEX idx_room_code ON classroom_locations(room_code);
CREATE INDEX idx_building ON classroom_locations(building);